-- MySQL Script generated by MySQL Workbench
-- Fri Jan 11 18:36:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payicam_shotgun
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `payicam_shotgun` ;

-- -----------------------------------------------------
-- Schema payicam_shotgun
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payicam_shotgun` DEFAULT CHARACTER SET utf8 ;
USE `payicam_shotgun` ;

-- -----------------------------------------------------
-- Table `payicam_shotgun`.`shotgun_choice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_shotgun`.`shotgun_choice` ;

CREATE TABLE IF NOT EXISTS `payicam_shotgun`.`shotgun_choice` (
  `choice_id` INT(4) NOT NULL,
  `choice_name` VARCHAR(50) NOT NULL,
  `choice_priceC` INT(5) NOT NULL,
  `choice_stock` INT(5) NOT NULL,
  `fk_desc_id` INT(4) NOT NULL,
  `payutc_art_idC` INT(11) NOT NULL,
  PRIMARY KEY (`choice_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_shotgun`.`shotgun_desc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_shotgun`.`shotgun_desc` ;

CREATE TABLE IF NOT EXISTS `payicam_shotgun`.`shotgun_desc` (
  `desc_id` INT(4) NOT NULL,
  `desc_titre` VARCHAR(50) NOT NULL,
  `desc_desc` TEXT NOT NULL,
  `desc_is_public` INT(1) NOT NULL,
  `desc_quota` INT(10) NOT NULL,
  `desc_debut` DATETIME NOT NULL,
  `desc_fin` DATETIME NOT NULL,
  `desc_public_cible` TEXT NOT NULL,
  `desc_site_cible` TEXT NOT NULL,
  `desc_email_cible` TEXT NULL DEFAULT NULL,
  `payutc_fun_id` INT(4) NOT NULL,
  `payutc_cat_id` INT(4) NOT NULL,
  PRIMARY KEY (`desc_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_shotgun`.`shotgun_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_shotgun`.`shotgun_option` ;

CREATE TABLE IF NOT EXISTS `payicam_shotgun`.`shotgun_option` (
  `option_id` INT(6) NOT NULL,
  `user_login` VARCHAR(125) NOT NULL,
  `user_prenom` VARCHAR(50) NOT NULL,
  `user_nom` VARCHAR(50) NOT NULL,
  `user_mail` VARCHAR(125) NOT NULL,
  `user_cotisant` INT(1) NOT NULL,
  `fk_desc_id` INT(5) NOT NULL,
  `fk_choice_id` INT(5) NOT NULL,
  `payutc_tra_id` INT(9) NOT NULL,
  `payutc_tra_url` VARCHAR(150) NOT NULL,
  `option_date_creation` DATETIME NOT NULL,
  `option_date_paiement` DATETIME NULL DEFAULT NULL,
  `option_status` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`option_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
